# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile*", "*.sh", "lib"]

#permalink: /blog/:title

# Site settings
title: Your awesome title
email: website@foolscap.org
title : "Foolscap: February 5–7, 2016, in Seattle, Washington"
tagline: "Join the conversation. Build the convention"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog

production_url : http://ghpages-test.foolscap.org/foolscapcon.github.io.testbed/
development_url : http://127.0.0.1:4000
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: foolscapcon
github_username:  foolscapcon

# Build settings
markdown: kramdown

gems: ["jekyll-sitemap"]
highlighter: rouge

encoding: UTF-8

